### ISSUE TITLE
How to configure eglot so it doesn't query the language server until it is ready

### ISSUE THREAD

**Issue by mgrojo** [brownts/dotemacs-ada#3]
I'm trying eglot and ada-ts-mode or ada-mode with a large code base at work. They work fine, but ada_language_server takes a long time to parse and index all files. There is a phase before the indexing message appears that you don't know in which state it is via Emacs, but I've traced the process and it's searching and reading sources and ALI files. While it is not ready, any query that eglot performs get queued and eventually times out. I wonder if this could be prevented, and whether it should be reported as an issue in ada_language_server or in eglot. At least some feedback about still not being ready would be needed, so you wait before expecting completion or navigation to work. Any help would be appreciated.

**Comment by brownts** [comment]
I don't think this is isolated to Eglot (or Emacs).  Even VSCode will start querying the Language Server before the project file has been processed.  I would first suggest checking which version of the Ada Language Server you are using.  The latest version (25.0.20240915) has a number of problems with it, apparently some of which were known but due to a process change they needed to release it.  Therefore, if the problems you are having started recently, I'd try rolling back to 24.0.6 and see if that fixes your issues.  With some large projects we use at work, this version causes navigation to be completely broken and we've had to revert to 24.0.6 for those projects.  I've reported a number of issues on this version through our support channel.

I assume when you mention the "indexing message", you're referring to the "$/progress" messages which show up in the mode line indicating the percentage (or number of files indexed status).  I agree that it can take some time before the Language Server even starts indexing, minutes maybe depending on the size of your project.  If you use aggregate projects, this can be even worse.  AdaCore has recommended not using aggregate projects with the Language Server.  My experience using them with ALS is that it seems it can have an exponential affect on project processing and indexing time.  I use to start VSCode and wait until the CPU usage for the Language Server dropped.  Could be up to 30 minutes later.  It was not uncommon for it to have consumed ~10G of RAM.  Eventually, it settles down and the resources drop down to a reasonable amount.  I think this has improved over time.  I haven't looked lately to see what the latest statistics are for some of the large projects.

If you have a support contract through your work, I'd recommend creating a customer support ticket for them.  They will respond to customer support with higher priority than issues logged through GitHub issues and is even how they recommend you contact them when you have a support contract.  Mention your concerns about not knowing what's going on before the indexing starts.  I assume there is no real difference here between VSCode behavior and Emacs/Eglot behavior.  Even if you don't have a support contract, it can't hurt creating an issue on their Github page.

**Comment by mgrojo** [comment]
Thanks for sharing your experience with ALS. In fact, I'm using an aggregate project and the latest ALS version, so I will try changing that. 

It's true that Emacs and VS Code seem to spend a similar time loading the project. The main difference is that VS Code only shows a "Loading..." tooltip when hovering and never blocks if you try to invoke a navigation operation. Eglot, on the other part, only shows pending requests in the modeline, and it will block Emacs if you try to go to the definition of an identifier. That's why you should know the state of ALS before making the request. In any case, if it cannot be avoided through configuration, it's just a matter of making sure ALS is responding to Eglot requests or waiting for the 100% message to appear.

I don't know if we have a support contract for this project, but I will ask.

**Comment by brownts** [comment]
>The main difference is that VS Code only shows a "Loading..." tooltip when hovering and never blocks if you try to invoke a navigation operation. Eglot, on the other part, only shows pending requests in the modeline, and it will block Emacs if you try to go to the definition of an identifier. That's why you should know the state of ALS before making the request.

Ah, that's a good point.  I haven't experimented with Eglot during this time period,  since I'd just wait until the indexing was done as I knew the navigation wouldn't work until then, but it makes sense that this could be an issue.  I assume that C-g won't get you out of that, correct?

If Eglot is freezing like this, I do wonder if maybe something couldn't be done on the Eglot side with a timeout.  I took a quick look at the Eglot settings, but didn't notice any timeout support except for the initial connection.  Might be good to ask about this on the Emacs mailing lists.

I think people are still logging issues/asking questions on the old Github [page](https://github.com/joaotavora/eglot) too, so you could probably ask there as well.
